language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hyunjin1612@gmail.com

before_deploy: # deploy명령어가 실행되기 전에 수행된다. AWS의 CodeDeploy는 Jar파일을 인식하지 못하므로, jar와 기타 설정 파일들을 모아 압축한다.
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성. Travis CI는 S3로 디렉토리 단위로만 업로드 할 수 있다.
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/springboot2-webservice.zip # deploy로 zip 파일 이동

deploy: # S3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선언
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis reop settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis reop settings에 설정된 값
    bucket: hyunjin-springboot2-webservice-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리. 해당 위치의 파일들만 S3로 전송.
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hyunjin-springboot2-webservice-build
    key: springboot2-webservice.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip #압축 확장자
    application: springboot2-webservice # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: springboot2-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait_until_deployed: true
