version: 0.0 # CodeDeploy 버전
os: linux
files:
  - source: / # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상 지정. 루트경로(/)를 지정하면 전체 파일을 이야기한다.
    destination: /home/ec2-user/app/step3/zip/ # source에서 지정된 파일을 받을 위치
    overwrite: yes # 기존에 파일들을 덮어쓸지 결정

permissions: # CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다.
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks: # CodeDeploy 배포 단계에서 실행할 명령어를 지정한다. ApplicationStart 단계에서 deploy.sh를 ec2-user 권한으로 실행하게 한다.
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료.
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링 부트 시작
      timeout: 60 # 스크립트 실행이 60초 이상 수행되면 실패.
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인.
      timeout: 60
      runas: ec2-user
